class Optional:
    optional = [
        'Comunicare si dezvoltare profesionala',
        'Programare in C',
        'Metode avansate de rezolvare a problemelor de matematica si informatica',
        'Automatizarea proceselor de business',
        'Baze de date spatiale',
        'Microcontroleri',
        'Criptografie cu cheie publica',
        'Grafica pe calculator',
        'Algebra computationala',
        'Protocoale specializate in retele de calculatoare',
        'Aspecte pragmatice în programare',
        'Realitate virtuala',
        'Metode inteligente de rezolvare a problemelor reale',
        'Interactiune om-calculator',
        'Securitate software',
        'Instrumente case',
        'Procesarea datelor audio-video',
        'Redactarea documentelor matematice in latex',
        'Tehnici de testare software',
        'Android things',
        'Administrare de sistem si retea',
        'Fundamentele limbajelor de programare',
        'Dezvoltarea jocurilor',
        'Business intelligence',
        'Sabloane de proiectare',
        'Instrumentatie virtuala',
        'Introducere in prelucrarea limbajului natural',
        'Proiectare avansată de compilatoare',
        'Paradigme şi tehnici ale programării paralele',
        'Tehnici de realizare a sistemelor inteligente',
        'Tehnici de optimizare',
        'Gestionarea proiectelor software',
        'Aspecte etice şi juridice în informatică',
        'Istoria informaticii',
        'Istoria matematicii',
        'Matematica de baza',
        'Aplicatii ale geometriei in informatica',
        'Geometrie 3(geometria diferentiala a curbelor si suprafetelor)',
        'Capitole speciale de ecuatii diferentiale',
        'Complemente de analiza matematica',
        'Teoria numerelor',
        'Complemete de geometrie',
        'Analiza functionala',
        'Astronomie',
        'Practica de specialitate',
        'Interactiunea om-calculator',
        'Prelucrarea imaginilor',
        'Interactiunea om-calculator',
        'Aspecte pragmatice in programare',
        'Metode inteligente de rezolvare a problemelor reale',
        'Aspecte pragmatice in programare'
        'Instruire asistata de calculator',
        'Cerc de programare in C',
        'Teoria si metodologia instruirii. Teoria si metodologia evaluarii',
        'Comunicare si dezvoltare profesionala in informatica',
        'Psihologie educationala'
    ]
    sport = 'Educatie Fizica'
    peda = ['Psihologie educationala', 'Teoria si metodologia instruirii. Teoria si metodologia evaluarii',
            "Instruire asistata de calculator", 'Practica pedagogica observativa']
