# Generated by Django 2.2.6 on 2019-10-17 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('group', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('professor', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('group', models.CharField(max_length=10)),
                ('start_time', models.TimeField()),
                ('duration', models.IntegerField(default=2)),
                ('frequency', models.IntegerField()),
                ('priority', models.CharField(max_length=30)),
                ('type', models.CharField(max_length=30)),
                ('description', models.TextField()),
            ],
            options={
                'unique_together': {('title', 'group', 'type')},
            },
        ),
    ]
