# Generated by Django 2.2.6 on 2019-10-31 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('professor', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('group', models.CharField(max_length=10)),
                ('start_time', models.TimeField()),
                ('duration', models.IntegerField(default=2)),
                ('frequency', models.CharField(max_length=5)),
                ('priority', models.CharField(max_length=30)),
                ('type', models.CharField(max_length=30)),
                ('description', models.TextField()),
            ],
            options={
                'unique_together': {('title', 'group', 'type')},
            },
        ),
        migrations.DeleteModel(
            name='Activity',
        ),
    ]
