# Generated by Django 2.2.6 on 2019-10-20 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='day',
            field=models.CharField(default='Monday', max_length=20),
        ),
    ]
