# Generated by Django 2.2.6 on 2019-11-26 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolactivity',
            name='day',
            field=models.CharField(max_length=15),
        ),
    ]
