# Generated by Django 2.2.8 on 2019-12-09 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_auto_20191126_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='peda',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='sport',
            field=models.BooleanField(default=False),
        ),
    ]
