# Generated by Django 2.2.6 on 2019-10-31 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_auto_20191031_0722'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='schoolactivity',
            unique_together=set(),
        ),
    ]
