# Generated by Django 2.2.8 on 2019-12-15 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_auto_20191209_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolactivity',
            name='location',
            field=models.CharField(default='FSEGA', max_length=255),
        ),
    ]
