# Generated by Django 2.2.6 on 2019-10-31 16:30


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_auto_20191031_0739'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schoolactivity',
            name='description',
        ),
    ]
