# Generated by Django 2.2.6 on 2019-11-01 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0004_remove_schoolactivity_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('start_time', models.TimeField()),
                ('day', models.CharField(max_length=15)),
                ('duration', models.IntegerField(default=2)),
                ('frequency', models.CharField(max_length=5)),
                ('priority', models.CharField(max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='schoolactivity',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='schoolactivity',
            name='frequency',
        ),
        migrations.RemoveField(
            model_name='schoolactivity',
            name='id',
        ),
        migrations.RemoveField(
            model_name='schoolactivity',
            name='location',
        ),
        migrations.RemoveField(
            model_name='schoolactivity',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='schoolactivity',
            name='start_time',
        ),
        migrations.RemoveField(
            model_name='schoolactivity',
            name='title',
        ),
        migrations.CreateModel(
            name='ExtraActivity',
            fields=[
                ('activity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='schedule.Activity')),
                ('description', models.TextField()),
            ],
            bases=('schedule.activity',),
        ),
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.Activity')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.User')),
            ],
        ),
        migrations.AddField(
            model_name='schoolactivity',
            name='activity_ptr',
            field=models.OneToOneField(auto_created=True, default='', on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='schedule.Activity'),
            preserve_default=False,
        ),
    ]
