# Generated by Django 2.2.6 on 2019-11-01 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0005_auto_20191101_1709'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserExtraActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extra_activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.ExtraActivity')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.User')),
            ],
        ),
        migrations.CreateModel(
            name='UserSchoolActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.SchoolActivity')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.User')),
            ],
        ),
        migrations.DeleteModel(
            name='UserActivity',
        ),
    ]
