# Generated by Django 2.2.6 on 2019-11-06 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0005_schoolactivity_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.AddField(
            model_name='user',
            name='photo_url',
            field=models.CharField(default='asd', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='uid',
            field=models.CharField(default='-1', max_length=255, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
