# Generated by Django 2.2.6 on 2019-11-26 15:04

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_auto_20191126_1704'),
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LastTimetable',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='schedule.User')),
                ('lastTimetable', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='preference',
            name='preference1',
        ),
        migrations.RemoveField(
            model_name='preference',
            name='preference1_prio',
        ),
        migrations.RemoveField(
            model_name='preference',
            name='preference2',
        ),
        migrations.RemoveField(
            model_name='preference',
            name='preference2_prio',
        ),
        migrations.RemoveField(
            model_name='preference',
            name='preference3',
        ),
        migrations.RemoveField(
            model_name='preference',
            name='preference3_prio',
        ),
        migrations.AddField(
            model_name='preference',
            name='fridayEnd',
            field=models.TimeField(default=datetime.time(20, 0)),
        ),
        migrations.AddField(
            model_name='preference',
            name='fridayStart',
            field=models.TimeField(default=datetime.time(8, 0)),
        ),
        migrations.AddField(
            model_name='preference',
            name='mondayEnd',
            field=models.TimeField(default=datetime.time(20, 0)),
        ),
        migrations.AddField(
            model_name='preference',
            name='mondayStart',
            field=models.TimeField(default=datetime.time(8, 0)),
        ),
        migrations.AddField(
            model_name='preference',
            name='thursdayEnd',
            field=models.TimeField(default=datetime.time(20, 0)),
        ),
        migrations.AddField(
            model_name='preference',
            name='thursdayStart',
            field=models.TimeField(default=datetime.time(8, 0)),
        ),
        migrations.AddField(
            model_name='preference',
            name='tuesdayEnd',
            field=models.TimeField(default=datetime.time(20, 0)),
        ),
        migrations.AddField(
            model_name='preference',
            name='tuesdayStart',
            field=models.TimeField(default=datetime.time(8, 0)),
        ),
        migrations.AddField(
            model_name='preference',
            name='wednesdayEnd',
            field=models.TimeField(default=datetime.time(20, 0)),
        ),
        migrations.AddField(
            model_name='preference',
            name='wednesdayStart',
            field=models.TimeField(default=datetime.time(8, 0)),
        ),
    ]
