# Generated by Django 2.2.6 on 2019-11-06 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='preference',
            name='preference1_prio',
            field=models.CharField(default='LOW', max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='preference',
            name='preference2_prio',
            field=models.CharField(default='LOW', max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='preference',
            name='preference3_prio',
            field=models.CharField(default='LOW', max_length=32),
            preserve_default=False,
        ),
    ]
